### ISSUE TITLE
loosing state (webpack) 

### ISSUE THREAD

**Issue by klaaz0r** [whitecolor/cycle-hmr#5]
I am trying to create HMR with webpack and keeping the cycle state, from the debug log I figure that cycle-hmr finds the files correct, I am using the webpack-dev-server cli to start but when starting it with the node api I get the same, after a reload state is reset. 

```[HMR] Waiting for update signal from WDS...
proxy.js:35 [Cycle HMR] proxy 198_app_index_default: execute
proxy.js:35 [Cycle HMR] proxy 198_app_index_default: created
proxy.js:35 [Cycle HMR] proxy 198_app_index_default: stream for sink DOM created, observers: 1
client?cd17:37 [WDS] Hot Module Replacement enabled.
2client?cd17:37 [WDS] App updated. Recompiling...
client?cd17:37 [WDS] App hot update...
dev-server.js:55 [HMR] Checking for updates on the server...
proxy.js:35[Cycle HMR] proxy 198_app_index_default: reload
log-apply-result.js:20 [HMR] Updated modules:
log-apply-result.js:22 [HMR]  - 198
dev-server.js:41 [HMR] App is up to date.```

**Comment by Widdershin** [comment]
This is fundamental to the design of how cycle-hmr works. The only project that maintains state for code reloading for Cycle is cycle-restart.

**Comment by wclr** [comment]
@klaaz0r what stream library do you use? This is how cycle-hmr reload works:

1) it loads new version of your component (_which is function_), 
2) then it passes to it the same sources (as to an old function), executes new version:
- this means all the streams created **inside** reloaded function will be of course recreated (and launched again)

3) subscribe proxy sinks to new sinks (to mimic them): 
- first proxy stream subscribe to new real sink, and then old sink is unsubscribed - this allows not to loose whole state.

So, eventually you "loose" only state of the internal streams of reloaded component (which is quite logical), if for example your component doesn't introduce any internal stream but just works with source streams, you should not loose state at all. 

As @Widdershin mentioned cycle-restart replaces the whole app (on any change) and tries to replay the history of all your sources to "recreate" you app's state - this is a whole different approach.
